### ISSUE TITLE
User can view their car(s) they own

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#1]
User can view a list of their cars

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/163025419-2ff8bc7c-c1f6-4a57-9622-3072ee2e9ac6.png)

![image](https://user-images.githubusercontent.com/48267398/163025372-bfcfb9fa-887f-4cd0-b064-3e48f87003f1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` with sql created from dbdesigner.
- [x] Update 'data.sql' with a 'mock' car

### ☁️ Server

- [x] Update 'server/index.js' with a GET request that receives each car owned by a user
- [x] Set the get request route to '/api/garage'
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the navbar
- [x] Create an offcanvas menu that will display when a menu button is clicked
- [x] Add a link in the menu that redirects to the 'garage' route
- [x] Update the 'home' component to render the navbar at the top of the screen
- [x] Create a 'my-garage' page for the user to view their car(s)
- [x] Create a MyCars class that will render the car(s) a user owns
- [x] Define a loadCars() function that will send a fetch request to get the year, make, and model of all cars in the user owns
- [x] Render a card with the vehicle image
- [x] Add car 'year', 'make', and  'model' as a title to the card
- [x] Add the vehicle's 'vehicleId' as a key to the React element.
- [x] Define a render() function and render any cars returned from loadCars(), if there are no values, it will display a 'no cars to display' message.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
