### ISSUE TITLE
User can view history of all repairs

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#11]
## ⚙️ Feature

User can see a grouped list of all their repairs performed on their vehicle

## 📐 Functionality

User can click on a link at the bottom of their 'recent records' table that takes them to another page that holds all their vehicle's records

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/164108074-1a287e25-0c23-47d0-a4a4-0114fc9a01c6.png)

![image](https://user-images.githubusercontent.com/48267398/164108223-a049e089-e874-4be6-bb7f-2cc8c47a7bb1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a get request for '/api/vehicles/:vehicleId/records'
- [x] Query the records table for all records with the matching vehicleId
- [x] Use json_agg and group by "datePerformed"::date to group the maintenance names together

### ⚡ Client

- [x] Create a page 'all-records' that will display  the user's records.
- [x] Add an anchor tag ('view all records') at the bottom of the 'recent records' table with an href to '#vehicle-records?vehicleId=${vehicleId}'
- [x] Add a conditional to app.jsx renderPage() method that renders the 'all-records' page when the hash route changes to all records
- [x] Create a class AllRecords and give it a state property of 'records'
- [x] Define a componentDidMount() method and send a fetch request to '/api/vehicles/${vehicleId}/records' and store the return into the records state
- [x] Define a method 'displayGroupedRecordsList' that loops through each grouped record and returns a list with the records name and cost
- [x] Define a 'render' method that will render an accordion that contains all the records
- [x] Map through each array item in the return of the groupRecordsByDate using the two previously defined methods
- [x] Assign the accordion item an eventKey of the array item's index
- [x] Display the total cost at the bottom of each group.
- [x] Make sure the correct number of grouped items appear 
- [x] Make sure the correct items appear in each group when that list item is clicked

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
