### ISSUE TITLE
User can edit details of their car

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#12]
## ⚙️ Feature

User will be able to edit their car's image, year, make, and model

## 📐 Functionality

User can click a button to bring up a form that allows them to enter a new year, make, model, and upload a new image for their car

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/164121644-9317aa45-39fb-40fa-9f68-0f3a6efec602.png)
![image](https://user-images.githubusercontent.com/48267398/164121881-9315f9ef-da39-4c3a-9282-fed8ae9ebdc4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a put route for '/api/garage/edit-car/:vehicleId'
- [x] Update the database with the items that the user submitted
- [x] Check if a new value was given by the user and update that value in the database if given

### ⚡ Client

- [x] In car-details page, add an icon in top right corner of car image that user can click on to open modal to edit their car
- [x] Create a car-form component and transfer the carForm method from my-garage into the new component.
- [x] Move the handleSubmit, handleChange, and toggleModal methods to the carForm component page
- [x] Test page and see if carForm still adds cars from the my-garage page
- [x] In my-garage page, pass a prop 'newCar' to the 'AddRecord' component with a value of 'true'
- [x] In carForm component, add a state property of 'newCar' and assign it to the this.props.newCar value
- [x] Pass the a prop 'newCar' to carForm component with the value of 'false' to be used for indicating that a car is being updated
- [x] Add a conditional to the 'Add Car' button that displays 'Add Car' if this.state.newCar is true and 'Save Changes' if this.state.newCar is false
- [x] In the handleSubmit method, add a conditional that sends the original fetch post request if this.state.newCar is true
- [x] Add a fetch put request that sends the user's new updates to  '/api/garage/edit-car/:vehicleId' if this.state.newCar is false
- [x] Populate input fields with the car's details when a user clicks on the edit-car form
- [x] Check and make sure only new information given updates the car
- [x] Check and make sure nothing is deleted if no new input is given

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
