### ISSUE TITLE
User can remove cars

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#13]
## ⚙️ Feature

User can delete a car from their garage

## 📐 Functionality

User can see a button that will allow them to remove a car from their garage

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/164558174-930ab744-9922-4427-931d-894441fc621e.png)

![image](https://user-images.githubusercontent.com/48267398/164558092-9ec5bd79-0e17-4954-8612-8e6d90236652.png)

![image](https://user-images.githubusercontent.com/48267398/164558130-00ae8258-9422-4b9a-b1db-272161a349cc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a delete route for `/api/garage/delete-car/${vehicleId}`
- [x] Query the 'vehicles' table and delete the vehicle that matches the vehicle id

### ⚡ Client
- [x] Add a 'trash' icon in the top right of the car image that the user can click
- [x] Create a state object property 'deleteModal' that holds a boolean value
- [x] Create a method that renders a modal when deleteModal property is true
- [x] When user clicks on the trash icon, have a modal pop up that asks if the user would like to delete the car
- [x] If the user clicks on the 'delete' button, delete the car from the cars array in the state
- [x] Send a fetch delete request that deletes the vehicle from the "vehicles" and all the records associated with the vehicle from the "records" table
- [x] If the user clicks on the 'close' button or on the background, close the modal
- [x] Check and make sure only the selected car gets deleted
- [x] Make sure the page re-renders when a car is deleted

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
