### ISSUE TITLE
User can update a repair

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#14]
## ⚙️ Feature

User can click on a repair and edit the inputs for that repair 

## 📐 Functionality

When user clicks on edit button, input boxes appear for the user to edit the items.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/166340300-be9e2a3f-13a5-4f8e-ad71-800789862f7a.png)
![image](https://user-images.githubusercontent.com/48267398/166340325-a5dbf52d-e402-49cd-950c-991a6433f196.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a put route for '/api/garage/:vehicleId/edit-records'
- [x] Query the database to update the old records where the vehicle id, date, name of maintenance, mileage, and cost match
- [x] update the matching record with new record given by user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update record list to have an edit button
- [x] When user clicks on edit button, display new page that allows them to edit the information
- [x] Display the information in input boxes
- [x] Create a 'save' button at the bottom that saves the input.
- [x] Send a put request to update the database with the new information
- [x] Create a 'cancel' button that resets the form when a user clicks cancel
- [x] Update the state records array with the new values at their index
- [x] Prevent user from being able to click another accordion when they are in editing mode
- [x] Calculate new total cost when user submits an edited cost
- [x] When user changes values of the input and saves, the new values are displayed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
