### ISSUE TITLE
User can delete record

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#15]
## ⚙️ Feature

User can delete a record from their record list
## 📐 Functionality

User can select an item from their record list, click a button, and be asked if they would like to delete an item.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/166586671-9c9d63bc-0ab0-4dd2-ab4f-3df09ae3827e.png)
![image](https://user-images.githubusercontent.com/48267398/166586725-ec129cfb-987c-4f8d-aa77-0ad166642b5f.png)
![image](https://user-images.githubusercontent.com/48267398/166586758-de32ad28-1c7f-4533-b6ba-b2df964bcfab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a delete route for '/api/garage/:vehicle-id/delete-record'
- [x] query the database to delete from records table where maintenanceName, cost, vehicleId, and datePerformed match the given values.

### ⚡ Client

- [x] Create a method that renders a modal that will ask to confirm to delete a record
- [x] When user clicks on a record, display a delete item button
- [x] Create a method that will toggle the modal by updating a toggleModal state
- [x] When user clicks on a record pop up a modal that will ask to delete that record
- [x] Make sure modal closes when cancel button or background is clicked
- [x] Create a method that will send a fetch delete request to delete the selected record
- [x] Update display to show the removed item
- [x] Make sure the total get updated when user removes an item.
- [x] When no more items exist for a given date, remove that accordion item from the display
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
