### ISSUE TITLE
User can view map of local mechanics

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#16]
## ⚙️ Feature

User can see a map that can display mechanics near them

## 📐 Functionality

User can click on a button to search their location for local mechanics

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/48267398/164845105-0c4b6f27-b392-4cbe-a32d-851ff5ec39f1.png)

![image](https://user-images.githubusercontent.com/48267398/164845128-aeb8865b-4ec2-44f1-a463-9d7bcfe61bbb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to render the map
- [x] Create a button that gets the user's location and take the coordinates of the user's location and store it in a variable
- [x] Create a marker that pops up when a user clicks the button for their location
- [x] Create an infowindow that pops up when a user clicks on the marker.
- [x] Use google PlacesService().textSearch() to find local mechanics based on a user's location
- [x] Create a marker for each result
- [x] Create an infowindow for each marker that pops up when a user clicks on the marker.
- [x] Create a state that holds the marker index number and pops up the corresponding infowindow.
- [x] Create a distinct marker that displays the user's location

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
