### ISSUE TITLE
User can upload receipt

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a receiptUrl column
- [x] Update `data.sql` with mock data that includes a receiptUrl

### ☁️ Server

- [x] Update `server/index.js` post route for add-record to include a receiptUrl.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] In the add-record modal, include a file upload option
- [x] Create a file upload ref
- [x] Create a container for all images to be rendered
- [x] Create a function maps through all receipt images and creates an image box
- [x] display all images in a row next to total value
- [x] when user clicks on image, enlarge image in modal
- [x] make sure image that is clicked is the image that pops up

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
