### ISSUE TITLE
User can add a car

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#2]
User can add a car they own to a list

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/162818501-1b1c9206-5a31-404c-95a3-e574ba23b784.png)
![image](https://user-images.githubusercontent.com/48267398/162818592-99e26738-fda0-493c-a0b0-a1d829adabf4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update `server/index.js` to handle a POST request to the database that will insert a 'year', 'make', and 'model'
- [x] Set the post request route to '/garage/add-car'
- [x] Add a condition that checks that year, make, and model are included and return an error if they are not
- [x] Query the database to insert the year, make, and model
- [x] Return the parsed JSON of the car's year, make, and model
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create a 'state' that holds the properties 'year', 'make', 'model'.
- [x] Add a '+' button that will display the 'Add Car' modal on click
- [x] Create an 'add-car'  component that renders a modal form for the user to input the car they own.
- [x] Add two buttons at the bottom of the form 'Add Vehicle' and 'Close'
- [x] Define a 'handleChange' function that sets the state of the year, make, model as the user inputs the information
- [x] Define a 'handleSubmit' function that will send a fetch request to post the user's information to the database.
- [x] Send the car's year, make, and model as a JSON to the post request in index.js when 'Add Vehicle'
- [x] Query the database to insert the car information into the 'vehicles' table
- [x] Render the return of the fetch post request when a user clicks 'Add Vehicle'
- [x] Check database and make sure that a new car was added.
- [x] Remove the modal from view after the user clicks 'Add Vehicle'
- [x] When user clicks on the 'Close' button or outside the modal, the form is cleared and the modal is removed from view.

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
