### ISSUE TITLE
User can upload picture of their car

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#21]
## ⚙️ Feature

User can upload a picture of their car when they add a car

## 📐 Functionality

When a user goes to add a new car, they now have the option to upload an image of their car

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/164287916-3199bfa3-8d52-4626-87c4-0993f4a00bda.png)

![image](https://user-images.githubusercontent.com/48267398/164288530-a88c7a91-d554-4f85-b5ee-a881287547e3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install the multer middleware and create a js file to mount the middleware
- [x] Import the middleware to the index.js file
- [x] Create a variable 'photoUrl' and assign it a value of /images/${req.file.filename}
- [x] Update the 'records' table with the 'photoUrl', 'year', 'make', and 'model' of the body
- [x] Create an 'images' folder within the 'public' folder to hold the images
- [x] in the post route for '/api/garage/add-car' add another db insert for the photoUrl that inserts the 'photoUrl' variable
- [x] If no photoUrl is provided by the user, insert the value of 'null' 

### ⚡ Client

- [x] Create a 'file upload' input box for the user to upload a file in the 'add vehicle' modal.
- [x] Assign this.fileInputRef with a value of React.createRef() to hold the file reference
- [x] Create a new FormData object and append the photo file and car title that the user submits
- [x] Send the FormData as the body for the fetch post request
- [x] Make sure form resets when user submits their data
- [x] Make sure the new car renders on the page with the image

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
