### ISSUE TITLE
User can view details of a car

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#3]
## ⚙️ Feature

User can view the details of a car they select from their garage

## 📐 Functionality

User will be able to click on a car they own from their list of cars and then be taken to a screen that displays the cars information

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/163455724-a075883f-4359-4fd3-9964-4cfd1896c8b3.png)
![image](https://user-images.githubusercontent.com/48267398/163455827-900c1395-d6f1-4e82-af87-34f8ad480494.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] Update 'data.sql' to insert mock records into the 'records' table
- [x] Check pgweb to make sure data is inserted

### ☁️ Server

- [x] Update `server/index.js` to listen for a get request for '/garage/:vehicleId'
- [x] Add a conditional that checks if a positive integer was given as a vehicleId
- [x] Query the database for the vehicleId in the 'vehicles' table for year, make, model, photoURL
- [x] Join records of the vehicle with matching vehicleId in the 'records' table.
- [x] Add a conditional that returns an error if no vehicle with that vehicle id has been found
- [x] Order the return by date descending order (most recent to oldest)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] In 'my-garage.jsx' wrap the car card in an anchor tag with an href of `#garage?vehicleId=${vehicleId}`
- [x] Add a 'hashchange' event listener in app.jsx (within componentDidMount) and set the 'route' state to  the new hash location
- [x] Create a 'car-detail' page that will render a car's details when the url is set to `#garage?vehicleId=${vehicleId}`
- [x] In the 'car-detail' page, send a fetch get request to '/garage/${vehicleId}' and set the state of 'carTitle' and 'carRecords' to the return
- [x] Create a div that holds the car's title (year, make, model)
- [x] Create an image container below the title that holds the car's photo
- [x] Create a table with a header of "Recent Records" that holds the most recent records
- [x] Render the 'date', 'record name(s)', and 'mileage' in the table
   - [x] Group records by 'date'
   - [x] Order the records by the most recent date
   - [x] If there are multiple records for that date, concatenate the names
   - [x] Display only the four most recent records
- [x] If there are no records to display, render a message that says 'No Records To Display'
- [x] Add a conditional within app.jsx render method that will render the 'car-detail' page if the the url is set to `#garage?vehicleId=${vehicleId}`
- [x] Add a conditional within app.jsx render method that will render the 'garage' page if the url is set to '#garage'
- [x] Check that user can swap between garage and car details without errors
- [x] Check that new car details are loaded when a different car is selected

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
