### ISSUE TITLE
User can  create an account

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#41]
## ⚙️ Feature

User can create an account with a username and password

## 📐 Functionality

User can see a screen that will allow them to create an account

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a post route to add a username and password to the database
- [x] Create a hashpassword file that will take the user's password and hash it
- [x] return the query to check if account was successfully created.

### ⚡ Client

- [x] Create a component to render a sign-up page
- [x] Update app.jsx to handle a hash route for the sign up page.
- [x] Update menu to have a link that takes user to sign up page.
- [x] In sign up page, create a form with two inputs for username and password
- [x] Create a state property that holds the inputted username and password
- [x] Create a handlechange function that updates the username and password as the user types
- [x] Create a handlesubmit function that sends a fetch request with the username and password
- [x] If account is created, display a message saying that account was created
- [x] If username already exists, display message that tells user that username already exists
- [x] Create condition that prevents user from creating account if username is less than 6 characters
- [x] Create condition that makes user's password have 6 characters, one uppercase, one lowercase, and one number in their password
- [x] Create states for uppercase, lowercase, and number that updates to true if user's password has each item
- [x] Create conditional rendering that displays a red text that tells user that they need a certain password requirement.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
