### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#43]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ☁️ Server
- [x] Install jswonwebtoken  and require the middleware
- [x] Update `server/index.js` to handle a post route for '/api/auth/sign-in' that will handle when a user logs in.
- [x] Check to make sure user provides a username and password, if not throw an error.
- [x] Query the database and check if a user with the provided username exists
- [x] Throw an error if no username exists
- [x] If there is a user, verify the given password with the hashed password in the database
- [x] Throw an error if there is no result (ie password does not match)
- [x] create a payload with the user id and username from the database query
- [x] sign a json webtoken with the payload that was created and a private key
- [x] send a status of 201 if successful as well as an object containing the payload and token
- [x] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to handle a sign in page
- [ ] 
### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
