### ISSUE TITLE
User can add record

### ISSUE THREAD

**Issue by luc-ky-khuu** [luc-ky-khuu/vehicle-expenses-tracker#6]
## ⚙️ Feature

User can fill out a form to enter repair records for a car they own

## 📐 Functionality

User can input information in a form about the repair of their card. Once submitted, they will see that repair in the most recent history

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/48267398/163629224-79b3eff1-17e3-457d-aca2-00ce5bcc8ebe.png)
![image](https://user-images.githubusercontent.com/48267398/163634783-a812c30b-c947-47b5-85c6-0fa1e9a9e707.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a post request to insert into the "records" table (date, price, maintenance, mileage, vehicleId)
- [x] Set the route for the post to '/api/garage/add-record/:vehicleId' and parse the req body
- [x] Insert the request into the records table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a form with four inputs (date, price, maintenance, mileage)
- [x] Update component with an 'add' button and a 'clear form' button
- [x] Add a handleSubmit function that takes the values of the user's inputs and sends the data in a fetch post request
- [x] Add a clearForm function that resets the form
- [x] When 'add' button is pressed, the user's data they entered get submitted
- [x] When 'clear form' button is pressed or the data has been submitted, the form is cleared
- [x] Add condition that checks to make sure all data has been entered correctly, display error message if data is missing
- [x] Add a fetch post request to `/api/garage/add-record/${vehicleId}` that sends the user's input via the body header
- [x] For mobile, create an offcanvas modal that displays the form when the specified icon is clicked.
- [x] For desktop, make sure the form is displayed when the screen is at desktop size.
- [x] Once data has been added, the 'Recent Records' table is updated with the maintenance that was added
- [x] Catch any errors

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
